### ISSUE TITLE
Download board filters are „scrambled“ on iPad

### ISSUE THREAD

**Issue by kelson42** [offspot/dashboard#18]
<img width="1024" alt="image" src="https://github.com/offspot/dashboard/assets/1029718/adb0ade8-3e35-450e-bacf-69c19eb737ee">

I would like:
* up and down arrow buttons beside each other (there is enough space)
* if „Language“ label has to be put on the top of the selector, then aligned properly: left for LTR, right otherwise
* Size/title switchers should be properly verticaly aligned with other inputs

**Comment by rgaudin** [comment]
I can reproduce on the mobile view. Happens in landscape mode.
