### ISSUE TITLE
Download Banner removal behavior

### ISSUE THREAD

**Issue by rgaudin** [offspot/dashboard#8]
Dashboard's Kiwix download banner can be closed to leave out useful space given downloading a reader is a less frequent (and usually one time) scenario.

Because devices are frequently shared, we've implemented it so the banner comes back after 1h.

https://github.com/offspot/imager-service/issues/409 is not satisfied with it and actually should a user accidentally close it, there is no way to make it come back.

What better solution could we have?

- lower expiration?
- restore banner on window closeed/opened
- restore banner on each download page access (my favorite in the list)
- something else?

**Comment by rgaudin** [comment]
@Popolechien @kelson42 WDYT?

**Comment by kelson42** [comment]
@rgaudin Put it below the list instead above. My global approach would have been to create a dedicated page and a proeminent link somewhere.

**Comment by rgaudin** [comment]
Done ; thank you for the suggestion 👍
